// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: permission.proto

package hrm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission int32

const (
	Permission_UNKNOWN             Permission = 0
	Permission_CAN_ADD_EMPLOYEE    Permission = 1
	Permission_CAN_VIEW_EMPLOYEE   Permission = 2
	Permission_CAN_MODIFY_EMPLOYEE Permission = 3
	Permission_CAN_Add_PAY         Permission = 4
	Permission_CAN_MODIFY_PAY      Permission = 5
	Permission_ADMIN               Permission = 6
	Permission_CAN_VIEW_SALARIES   Permission = 7
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "UNKNOWN",
		1: "CAN_ADD_EMPLOYEE",
		2: "CAN_VIEW_EMPLOYEE",
		3: "CAN_MODIFY_EMPLOYEE",
		4: "CAN_Add_PAY",
		5: "CAN_MODIFY_PAY",
		6: "ADMIN",
		7: "CAN_VIEW_SALARIES",
	}
	Permission_value = map[string]int32{
		"UNKNOWN":             0,
		"CAN_ADD_EMPLOYEE":    1,
		"CAN_VIEW_EMPLOYEE":   2,
		"CAN_MODIFY_EMPLOYEE": 3,
		"CAN_Add_PAY":         4,
		"CAN_MODIFY_PAY":      5,
		"ADMIN":               6,
		"CAN_VIEW_SALARIES":   7,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

var File_permission_proto protoreflect.FileDescriptor

var file_permission_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0xa6, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x43, 0x41, 0x4e, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x4d, 0x50, 0x4c, 0x4f, 0x59,
	0x45, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x41, 0x4e, 0x5f, 0x56, 0x49, 0x45, 0x57,
	0x5f, 0x45, 0x4d, 0x50, 0x4c, 0x4f, 0x59, 0x45, 0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x43,
	0x41, 0x4e, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f, 0x45, 0x4d, 0x50, 0x4c, 0x4f, 0x59,
	0x45, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x4e, 0x5f, 0x41, 0x64, 0x64, 0x5f,
	0x50, 0x41, 0x59, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x41, 0x4e, 0x5f, 0x4d, 0x4f, 0x44,
	0x49, 0x46, 0x59, 0x5f, 0x50, 0x41, 0x59, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x41, 0x4e, 0x5f, 0x56, 0x49, 0x45, 0x57,
	0x5f, 0x53, 0x41, 0x4c, 0x41, 0x52, 0x49, 0x45, 0x53, 0x10, 0x07, 0x42, 0x06, 0x5a, 0x04, 0x2f,
	0x68, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData = file_permission_proto_rawDesc
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_permission_proto_rawDescData)
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_goTypes = []interface{}{
	(Permission)(0), // 0: Permission
}
var file_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_permission_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_rawDesc = nil
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
